### ISSUE TITLE
folder crawling stops after a while [windows]

### ISSUE THREAD

**Issue by MarcoFR** [francelabs/datafari#21]
I was able to follow the video tutorial to index a folder of documents.
Looks like the crawling job in manifoldCF stops after a while (loose connection ?)
118771 [http-bio-8080-exec-11] ERROR org.apache.solr.servlet.SolrDispatchFilter
 û null:ClientAbortException:  java.net.SocketException: Connection reset by pee
r: socket write error
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:
364)
        at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:32
6)
        at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputSt
ream.java:101)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at org.apache.solr.util.FastWriter.flush(FastWriter.java:137)

**Comment by otavard** [comment]
The Windows version is not our priority for now. We advise to use Docker version of Datafari if you are on Windows.
