### ISSUE TITLE
Erreur 404 Datafari 5

### ISSUE THREAD

**Issue by junfan59** [francelabs/datafari#59]
Hi,

I installed Datafari 5 for test purpose on Debian 10 but I get a 404.

After many reinstall I get some errors : 

When I start Datafari with  "./start-datafari.sh" Solr can't start : 
`"Waiting up to 180 seconds to see Solr running on port 8983 [-]  Still not seeing Solr listening on 8983 after 180 seconds!"`
I tried to start Solr alone but same issue.

Into log there is : 

solr-8983-console.log :

```
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
ERROR StatusLogger File not found in file system or classpath: /conf/log4j2.xml
ERROR StatusLogger Reconfiguration failed: No configuration found for '4dcbadb4' at 'null' in 'null'
java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
    at org.eclipse.jetty.start.Main.start(Main.java:491)
    at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1837)
    ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:762)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:757)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:973)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:940)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:512)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1060)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1638)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1539)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newArray(XmlConfiguration.java:1208)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1642)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1539)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:568)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:506)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1060)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1638)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1539)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:568)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:506)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1060)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:518)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:454)
    at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:354)
    at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$0(XmlConfiguration.java:1874)
    ... 9 more
Caused by: java.lang.IllegalArgumentException: Bad pattern: server-1-test.domaine.fr
    at org.eclipse.jetty.util.InetAddressSet.newInetRange(InetAddressSet.java:89)
    at org.eclipse.jetty.util.InetAddressSet.add(InetAddressSet.java:58)
    at org.eclipse.jetty.util.InetAddressSet.add(InetAddressSet.java:51)
    at org.eclipse.jetty.util.IncludeExcludeSet.include(IncludeExcludeSet.java:143)
    at org.eclipse.jetty.server.handler.InetAccessHandler.include(InetAccessHandler.java:77)
    ... 36 more
Caused by: java.net.UnknownHostException: server-1-test.dom: Nom ou service inconnu
    at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
    at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
    at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
    at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
    at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
    at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
    at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
    at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
    at org.eclipse.jetty.util.InetAddressSet.newInetRange(InetAddressSet.java:74)
    ... 40 more
    Suppressed: java.lang.IllegalArgumentException: Bad legacy pattern: server-1-test.domaine.fr
        at org.eclipse.jetty.util.InetAddressSet$LegacyInetRange.<init>(InetAddressSet.java:295)
        at org.eclipse.jetty.util.InetAddressSet.newInetRange(InetAddressSet.java:83)
        ... 40 more
java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
    at org.eclipse.jetty.start.Main.start(Main.java:491)
    at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1837)
    ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:762)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:757)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:973)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:940)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:512)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1060)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1638)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1539)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newArray(XmlConfiguration.java:1208)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1642)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1539)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:568)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:506)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1060)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1638)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1539)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:568)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:506)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1060)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:518)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:454)
    at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:354)
    at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$0(XmlConfiguration.java:1874)
    ... 9 more
Caused by: java.lang.IllegalArgumentException: Bad pattern: server-1-test.domaine.fr
    at org.eclipse.jetty.util.InetAddressSet.newInetRange(InetAddressSet.java:89)
    at org.eclipse.jetty.util.InetAddressSet.add(InetAddressSet.java:58)
    at org.eclipse.jetty.util.InetAddressSet.add(InetAddressSet.java:51)
    at org.eclipse.jetty.util.IncludeExcludeSet.include(IncludeExcludeSet.java:143)
    at org.eclipse.jetty.server.handler.InetAccessHandler.include(InetAccessHandler.java:77)
    ... 36 more
Caused by: java.net.UnknownHostException: server-1-test.dom: Nom ou service inconnu
    at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
    at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
    at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
    at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
    at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
    at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
    at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
    at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
    at org.eclipse.jetty.util.InetAddressSet.newInetRange(InetAddressSet.java:74)
    ... 40 more
    Suppressed: java.lang.IllegalArgumentException: Bad legacy pattern: server-1-test.domaine.fr
        at org.eclipse.jetty.util.InetAddressSet$LegacyInetRange.<init>(InetAddressSet.java:295)
        at org.eclipse.jetty.util.InetAddressSet.newInetRange(InetAddressSet.java:83)
        ... 40 more

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
```

My solr versioon is 8.5.2

Java version : 
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.11+9-post-Debian-1deb10u1, mixed mode, sharing)

solr_gc.log :
```
[2021-05-06T15:13:51.004+0200][0.003s] Heap region size: 4M
[2021-05-06T15:13:51.020+0200][0.019s] Using G1
[2021-05-06T15:13:51.020+0200][0.019s] Heap address: 0x00000000c0000000, size: 1024 MB, Compressed Oops mode: 32-bit
[2021-05-06T15:13:51.020+0200][0.019s] Mark closed archive regions in map: [0x00000000ffc00000, 0x00000000ffc6aff8]
[2021-05-06T15:13:51.020+0200][0.019s] Mark open archive regions in map: [0x00000000ffb00000, 0x00000000ffb46ff8]
[2021-05-06T15:13:51.748+0200][0,746s] Heap
[2021-05-06T15:13:51.748+0200][0,746s]  garbage-first heap   total 1048576K, used 36552K [0x00000000c0000000, 0x0000000100000000)
[2021-05-06T15:13:51.748+0200][0,746s]   region size 4096K, 9 young (36864K), 0 survivors (0K)
[2021-05-06T15:13:51.748+0200][0,746s]  Metaspace       used 9115K, capacity 9461K, committed 9728K, reserved 1058816K
[2021-05-06T15:13:51.748+0200][0,746s]   class space    used 1063K, capacity 1169K, committed 1280K, reserved 1048576K
```
 

During my last install the is some other errors : 

```
...
chown: impossible d'accéder à '/opt/datafari/tomcat/webapps/Datafari/resources/images/elevate.png': Aucun fichier ou dossier de ce type
chown: impossible d'accéder à '/opt/datafari/tomcat/webapps/Datafari/resources/images/not-available.png': Aucun fichier ou dossier de ce type
chown: impossible d'accéder à '/opt/datafari/tomcat/webapps/Datafari/resources/images/datafari.png': Aucun fichier ou dossier de ce type
chown: impossible d'accéder à '/opt/datafari/tomcat/webapps/Datafari/resources/images/search.png': Aucun fichier ou dossier de ce type
chown: impossible d'accéder à '/opt/datafari/tomcat/webapps/Datafari/index.jsp': Aucun fichier ou dossier de ce type
chown: impossible d'accéder à '/opt/datafari/tomcat/webapps/Datafari/help.jsp': Aucun fichier ou dossier de ce type
...
```

-----

```
Cassandra process running with PID 114985 --- OK
Waiting up until 180 seconds to see Cassandra running...
/!\ ERROR: Cassandra startup has ended with errors; please check log file /opt/datafari/logs/cassandra-startup.log

Warning: Cannot create directory at `/root/.cassandra`. Command history will not be saved.

Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})

Warning: Cannot create directory at `/root/.cassandra`. Command history will not be saved.

Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
```

-----

```

Exception in thread "main" org.apache.solr.common.SolrException: java.util.concurrent.TimeoutException: Could not connect to ZooKeeper localhost:2181 within 30000 ms
    at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:202)
    at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:126)
    at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:116)
```

-----

```
MCF Agent started with PID 116579
*** [WARN] *** Your open file limit is currently 16384.  
 It should be set to 65000 to avoid operational disruption.
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
*** [WARN] ***  Your Max Processes Limit is currently 63952.
 It should be set to 65000 to avoid operational disruption.
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
Waiting up to 180 seconds to see Solr running on port 8983 [\]  
Started Solr server on port 8983 (pid=116655). Happy searching!
```

-----

```
Wait 5s that Solr registers to Zookeeper...
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.</title>
</head>
<body><h2>HTTP ERROR 404 javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.</h2>
<table>
<tr><th>URI:</th><td>/solr/admin/configs</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.</td></tr>
<tr><th>SERVLET:</th><td>default</td></tr>
<tr><th>CAUSED BY:</th><td>javax.servlet.ServletException: javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.</td></tr>
<tr><th>CAUSED BY:</th><td>javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.</td></tr>
</table>
<h3>Caused by:</h3><pre>javax.servlet.ServletException: javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
```

-----

Into cassandra-startup.log first line : OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
and below :
```
INFO  17:29:47 DiskAccessMode 'auto' determined to be mmap, indexAccessMode is mmap
INFO  17:29:47 Global memtable on-heap threshold is enabled at 251MB
INFO  17:29:47 Global memtable off-heap threshold is enabled at 251MB
WARN  17:29:47 Only 33,549GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
ERROR 17:29:47 Port already in use: 7199; nested exception is:
    java.net.BindException: Adresse déjà utilisée (Bind failed)
java.net.BindException: Adresse déjà utilisée (Bind failed)
```

Thanks for help !

**Comment by bloubi** [comment]
Hi,

from what you're saying, it's hard to tell what is wrong, as you seem to have followed the procedure, but the devil is in the details. 
The one thing we can say, is that your Debian is not completely virgin since you at least have docker configured and running. Many things can get into the way of a Datafari install because of the numerous components it installs, so we always recommend dedicating the machine only to that, and without installing anything else upfront.

But since you are already running docker, what  why don't you try using the container image of Datafari that is available on docker hub ?

Regards,

Cedric

**Comment by junfan59** [comment]
Hi,
You're right I will use the docker container..

Thanks

**Comment by bloubi** [comment]
Hi,

did you have more success playing with the container version ?

Regards,

Cedric

**Comment by junfan59** [comment]
Yes, it's working :)
I will call soon Francelabs about commercial solution to know for example how to pass trought a SSO like CaS (https://fr.wikipedia.org/wiki/Central_Authentication_Service), the use inside TYPO3 CMS and some others questions.

Regards
